### ISSUE TITLE
Intergrate

### ISSUE THREAD

**Issue by santhosh-pro** [PetrovskiAlex/Outbox#1]
How to add in startup.cs?. Please make extension class or give any sample app used this library

**Comment by PetrovskiAlex** [comment]
Hi, I will add a background service, and give you an example how to use it

**Comment by PetrovskiAlex** [comment]
I added extension classes. So you can add: services.AddEfOutbox<YourEfDbContext>() or  services.AddNeo4JOutbox() in your Startup.cs. 
Note: this library uses Masstransit

If you have any question, please let me know.

**Comment by santhosh-pro** [comment]
Thank you. you made my day simple.
